elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
  container_name: elasticsearch
  environment:
    - xpack.security.enabled=false
    - http.host=0.0.0.0
    - transport.host=127.0.0.1
    - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65536
      hard: 65536
  mem_limit: 2560m
  cap_add:
    - IPC_LOCK
  volumes:
    - /usr/share/elasticsearch/data
  ports:
    - 9200:9200

kibana:
  image: docker.elastic.co/kibana/kibana:5.3.1
  container_name: kibana
  links:
    - elasticsearch
  ports:
    - 5601:5601
